baseurl: # the subpath of your site, e.g. /blog
url: https://joanabbrito.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Configuration variables
title: Joana Brito
description: My website

# Build settings
#theme: minima
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
