baseurl: # the subpath of your site, e.g. /blog
url: https://joanabbrito.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
#theme: minima
remote-theme: al-folio
plugins:
  - jekyll-feed
